#端口号配置
server:
  port: 8088

#ioc相关配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: iot
    password: iot
    url: jdbc:mysql://81.68.67.66/managerment?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  data: # 连接空闲超过N(s秒、ms毫秒)后关闭，0为禁用，这里配置值和tcp-keepalive值一致
    redis:
      database: 0 # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
      host: 81.68.67.66
      port: 9801
      password: iot
  mail:
    username: 19890534663@163.com
    host: smtp.163.com
    password: DQHLTODMOKAGTXMO
#mybatis 相关配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.securityclass.entity
  configuration:
    map-underscore-to-camel-case: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.securityclass.entity


logging:
  level:
    org.mybatis: DEBUG


upload:
  #directory: /home/ubuntu/web/upload
  directory: d:/upload/
